### ISSUE TITLE
Question of the impact of using pre-trained checkpoint mae_pretrain_vit_base.pth?

### ISSUE THREAD

**Issue by GWwangshuo** [junkunyuan/HAP#1]
Thank you for your intriguing work. The idea is both simple and effective. While pretraining HAP on LUPerson, I observed that you initialized the model using the pre-trained checkpoint mae_pretrain_vit_base.pth. Have you considered the potential impact on performance if we were to initialize the model from scratch during the pretraining of HAP on LUPerson?

**Comment by junkunyuan** [comment]
> Thank you for your intriguing work. The idea is both simple and effective. While pretraining HAP on LUPerson, I observed that you initialized the model using the pre-trained checkpoint mae_pretrain_vit_base.pth. Have you considered the potential impact on performance if we were to initialize the model from scratch during the pretraining of HAP on LUPerson?

We previously trained HAP from scratch, resulting in a performance decrease of approximately 2% and 5% on Market1501 and MSMT17, respectively.
