### ISSUE TITLE
Setting about layer-wise lr decay

### ISSUE THREAD

**Issue by githubiubiu** [junkunyuan/HAP#11]
Thank you for your great work. I have found that 'layer-wise lr decay' (default is 0.4 in person reid) greatly affects performance during fine-tuning, but I am not sure if this parameter should be bound to the size of the model (such as vit base, vit size) or to the dataset (i.e. different datasets/tasks require different settings). I have replicated it on other datasets, could you give me some guidance on setting this parameter? Thank you very much!

**Comment by junkunyuan** [comment]
> Thank you for your great work. I have found that 'layer-wise lr decay' (default is 0.4 in person reid) greatly affects performance during fine-tuning, but I am not sure if this parameter should be bound to the size of the model (such as vit base, vit size) or to the dataset (i.e. different datasets/tasks require different settings). I have replicated it on other datasets, could you give me some guidance on setting this parameter? Thank you very much!


I have also observed that this parameter has an impact on the results. 

However, I regret to inform you that I have not come across a definitive rule for tuning it. 

My only suggestion would be to employ grid search as a method for finding the optimal value for different models or datasets.
