### ISSUE TITLE
人体属性RAP实验结果疑问

### ISSUE THREAD

**Issue by lin-honghui** [junkunyuan/HAP#2]
从代码看论文RAP实验结果是RAPv1，对比的论文结果（UniHCP、PATH...）贴的却是RAPv2的实验结果。

**Comment by junkunyuan** [comment]
感谢指出这个问题。实验的对比确实不完全公平。
我们用的是Rethinking_of_PAR的代码，HAP在和Rethinking_of_PAR以及MAE这个baseline对比的时候是公平的。

**Comment by junkunyuan** [comment]
感谢指出这个问题。实验的对比确实不完全公平。
我们用的是Rethinking_of_PAR的代码，至少HAP在和Rethinking_of_PAR以及MAE这个baseline对比的时候是完全公平的。
