### ISSUE TITLE
More pretrained models

### ISSUE THREAD

**Issue by Zhenghongwei0929** [junkunyuan/HAP#3]
Thanks for your impressive work! Could you please provide more pretrained models ?

**Comment by junkunyuan** [comment]
Our current plan is to release the standard pre-trained checkpoint, which can be used to reproduce the results reported in Table 1.

**Comment by Zhenghongwei0929** [comment]
So do you mean that the current ckpt can reproduce all the results of tab1? If possible, is it convenient to provide more ckpt (such as different vit structures), thank you very much!

**Comment by junkunyuan** [comment]
> So do you mean that the current ckpt can reproduce all the results of tab1? If possible, is it convenient to provide more ckpt (such as different vit structures), thank you very much!

1. Yes, the pre-trained checkpoint we provided can reproduce Table 1.
2. We did not use other vit structures.
