### ISSUE TITLE
person_reid

### ISSUE THREAD

**Issue by yu9s** [junkunyuan/HAP#6]
hello!
    Thank you for your work。
     For person reid task, May I ask how should I train with multiple gpus?
     Looking forward to your reply.

**Comment by junkunyuan** [comment]
Our code only supports training with a single GPU.

For training with multiple GPUs, you may consider the use of [TransReID](https://github.com/damo-cv/TransReID).

**Comment by yu9s** [comment]
> Our code only supports training with a single GPU.
> 
> For training with multiple GPUs, you may consider the use of [TransReID](https://github.com/damo-cv/TransReID).

很抱歉打扰您，我想再问下，您提供的开源模型，我应该怎么测试person_reid任务呢? 比如rank1和map

**Comment by junkunyuan** [comment]
> > Our code only supports training with a single GPU.
> > For training with multiple GPUs, you may consider the use of [TransReID](https://github.com/damo-cv/TransReID).
> 
> 很抱歉打扰您，我想再问下，您提供的开源模型，我应该怎么测试person_reid任务呢? 比如rank1和map


您可以参考TransReID的代码说明，加载HAP的预训练权重后训练Person ReID任务。

如果您觉得麻烦，建议使用我们的单卡训练代码。

**Comment by yu9s** [comment]
> > > Our code only supports training with a single GPU.
> > > For training with multiple GPUs, you may consider the use of [TransReID](https://github.com/damo-cv/TransReID).
> > 
> > 
> > 很抱歉打扰您，我想再问下，您提供的开源模型，我应该怎么测试person_reid任务呢? 比如rank1和map
> 
> 您可以参考TransReID的代码说明，加载HAP的预训练权重后训练Person ReID任务。
> 
> 如果您觉得麻烦，建议使用我们的单卡训练代码。

ok，谢谢您，我这边今天直接用单卡训练了，20个epoch达到了95的rank1.

还有个问题就是ckpt_default_pretrain_pose_mae_vit_base_patch16_LUPersonPose_399.pth这个预训练模型其实我有点不明白怎么去直接测试reid的rank1和map。我看您的论文实验数据，这个模型在reid任务上性能挺好的，我想请教下，这个预训练模型，测试reid性能有没有参考代码，我想和微调出来的模型做个对比。

**Comment by junkunyuan** [comment]
> > > > Our code only supports training with a single GPU.
> > > > For training with multiple GPUs, you may consider the use of [TransReID](https://github.com/damo-cv/TransReID).
> > > 
> > > 
> > > 很抱歉打扰您，我想再问下，您提供的开源模型，我应该怎么测试person_reid任务呢? 比如rank1和map
> > 
> > 
> > 您可以参考TransReID的代码说明，加载HAP的预训练权重后训练Person ReID任务。
> > 如果您觉得麻烦，建议使用我们的单卡训练代码。
> 
> ok，谢谢您，我这边今天直接用单卡训练了，20个epoch达到了95的rank1.
> 
> 还有个问题就是ckpt_default_pretrain_pose_mae_vit_base_patch16_LUPersonPose_399.pth这个预训练模型其实我有点不明白怎么去直接测试reid的rank1和map。我看您的论文实验数据，这个模型在reid任务上性能挺好的，我想请教下，这个预训练模型，测试reid性能有没有参考代码，我想和微调出来的模型做个对比。

论文报告的就是ckpt_default_pretrain_pose_mae_vit_base_patch16_LUPersonPose_399.pth在ReID任务上微调后的精度。

ckpt_default_pretrain_pose_mae_vit_base_patch16_LUPersonPose_399.pth是预训练模型，不具有任务能力，无法直接在ReID任务上测试精度。
