### ISSUE TITLE
training logs on LUPerson dataset

### ISSUE THREAD

**Issue by Rockyman-star** [junkunyuan/HAP#8]
Thanks for your excellent work! I am trying to reproduce this repo. Could you please provide the training logs ```result.txt``` on LUP?

**Comment by junkunyuan** [comment]
> Thanks for your excellent work! I am trying to reproduce this repo. Could you please provide the training logs `result.txt` on LUP?

Apologies for the inconvenience, but unfortunately, we did not save the training logs. 

However, I want to assure you that after the paper was accepted, we made efforts to reproduce the results by re-pretraining the model. Based on our results, we are confident that the results presented in the paper can be reproduced if you follow the instructions provided.
