### ISSUE TITLE
CAE pre-trained checkpoint

### ISSUE THREAD

**Issue by Zoesxw** [junkunyuan/HAP#9]
Thank you for your excellent work!
In the paper, HAP with CAE is superior than with MAE on reid. Can you provide CAE based pre-trained checkpoint?
Thank you so much.

**Comment by junkunyuan** [comment]
> Thank you for your excellent work!
> In the paper, HAP with CAE is superior than with MAE on reid. Can you provide CAE based pre-trained checkpoint?
> Thank you so much.

Apologies, but unfortunately, we didn't save the CAE checkpoint.

Our primary implementation is based  MAE, while CAE was an additional attempt.

If you're interested in obtaining the CAE checkpoint, you may need to reproduce it on your own.

To get started, you can download the initial checkpoint for pre-training from [here](https://github.com/lxtGH/CAE).

Thank you for your understanding.
